---

- name: ping
  hosts: group_wordpress
  become: yes
  tasks:
    - name: ric_ping_serv
      ping:

# PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install php
      package:
        name: "{{ item }}"
        state: present
